### ISSUE TITLE
Problem in file "pico_i2c_lcd.py" line 22

### ISSUE THREAD

**Issue by stevensarns** [T-622/RPI-PICO-I2C-LCD#16]
Hello and thanks for the LCD code.  I have a Pi Pico W, Windows 10, Thonny 4.1.4 on COM7, 2x16 LCD. I have written and run several small test programs successfully including an i2c scan which shows LCD on 0x27 when run both from "computer" and "pi".  I have modified pico_i2c_test.py to support my hookup and slowing the clock freq:
I2C_NUM_ROWS = 2
I2C_NUM_COLS = 16
i2c = I2C(0, sda=machine.Pin(20), scl=machine.Pin(21), freq=100000)
Copied 3 files to Pi without renaming.  However, when I run pico_i2c_test.py I get the following error:

MPY: soft reboot
Running test_main
Traceback (most recent call last):
  File "<stdin>", line 62, in <module>
  File "<stdin>", line 16, in test_main
  File "pico_i2c_lcd.py", line 22, in __init__
OSError: [Errno 5] EIO

This is referencing this line 22 in pico_i2c_lcd.py:
        self.i2c.writeto(self.i2c_addr, bytes([0])) # (this statement fails - put "print" statements before & after)

Note that a scan does detect i2c on 0x27.  Rewired with shorter leads and slowed i2c clock -> no joy.  I am not an accomplished Python programmer and consequently cannot troubleshoot the problem any further.  Thanks again for any help.

So! This is just for your chuckles and anyone else who might have the same problem.  After spending hours on the problem, while hooking up my scope to SCL and SDA the system rebooted and works!

**Comment by petaramesh** [comment]
Hi there,
What you report is not a problem with the library, but an I/O error cause either by the fact that your LCD is not properly connected or powered, or connected to the wrong pins, or the pins aren't properly initialized or whatever.
Not a library issue anyway.
